version: "3.1"

services:
    
    webhook_database:
        image: "mongo"
        restart: "on-failure"
        container_name: "mongodb"
        ports:
            - "27117:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: "webhook_database"